### ISSUE TITLE
VM Backup script

### ISSUE THREAD

**Issue by feldsam** [cyborgbackup/cyborgbackup#16]
Hello @GaetanF, thanks for your exceptional work. I am looking into VM module docs, and I like to contribute to your project. My VM backup process is as follow:

- call OpenNebula API and create a disk snapshot
- call 3PAR API and export snapshot via FiberChannel to the backup server
- discover new LUN on the backup server
- do dd if | `borg create...`
- flush LUN from the backup server
- call 3PAR API and unexport snapshot
- call OpenNebula API and delete the snapshot

In VM module docs you write, that script has to return data to stdout, and you pass it to `borg create`, which is fine, but I need to post backup tasks, flush LUN, unexport, delete...

Would you point me to source code, where I should do extension?

Thanks!

**Comment by GaetanF** [comment]
Hello @feldsam,

You need to change the borg command used by CyBorgBackup. You can find them in the build_borg_cmd function in main/tasks.py.

This function check the policy type and pull/push mode to build the borg backup command launch on the client/hypervisor.

I think i can integrate a pre/post backup command/script in the VM module.

Regards
