### ISSUE TITLE
cyborg start (more a st***d question?)

### ISSUE THREAD

**Issue by janszczepanski** [cyborgbackup/cyborgbackup#17]
Hi,
I've installed cyborg successfully. But it doesn't start. No info / documentation about how to start it or fixing issues. Nginx displays just a 502 gateway error after install.

**Comment by v1ru535** [comment]
Doc is here:
https://cyborgbackup.readthedocs.io/en/latest/

**Comment by GaetanF** [comment]
Hello,

Wich install method have you used ?
Did you have some errors on the log file ?

Regards
