### ISSUE TITLE
proxy_pass nginx always redirect base

### ISSUE THREAD

**Issue by v1ru535** [cyborgbackup/cyborgbackup#18]
Hi

First of all, thanks for your great work.

I want to set nginx in front of docker port (bind 127.0.0.1) with proxy_pass.
But I didn't find the right configuration for it to work.
Always redirect to my domain name base on "auth.html".
But I want to stay on my domain name base with "cyborgbackup" after like that:
```
https://myndd/cyborgbackup/
```
I've try to redirect all to "static" but didn't work too.
```
For example:
https://myndd/cyborgbackup/
redirect:
https://myndd/auth.html
Result naturely 404.
```
I've try lot of option but don't find the good one:
```
proxy_redirect off;
proxy_redirect http://cyborgbackup http://$host;
proxy_set_header Host $host;
rewrite /cyborgbackup/(.*) /$1 break;
proxy_pass http://cyborgbackup/;
proxy_pass http://cyborgbackup;
proxy_pass http://cyborgbackup/$1;
```
_(upstream cyborgbackup 8000)_

If you've an idea :)

Thanks and have a good day!

**Comment by GaetanF** [comment]
Hello, 

If i remember, the UI interface have this own path hardcoded and must be rewritten.
I haven't found the solution for the moment.

Regards

**Comment by GaetanF** [comment]
Hello,

I'm currently develop a new version of the UI who permit the move of the base to a subfolder.

Regards

**Comment by GaetanF** [comment]
The new release with the new UI have been released.

This issue has been fixed
