### ISSUE TITLE
Authentification sur l'api

### ISSUE THREAD

**Issue by Grounz** [cyborgbackup/cyborgbackup#19]
Bonjour,

Quelle est le paramètre à utiliser pour s'authentifier sur l'api de cyborg afin d'effectuer des actions automatisées ?
J'ai beau lire et relire la documentation je ne trouve aucune information sur ce sujet.

**Comment by GaetanF** [comment]
Bonjour,

Je me base sur Django Rest Framework, il faut regarder la partie Token de Django Rest => https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication
