### ISSUE TITLE
 How to backup separate directories?

### ISSUE THREAD

**Issue by uFojun** [cyborgbackup/cyborgbackup#20]

**Comment by GaetanF** [comment]
Hello,

Actually, Cyborg didn't have a policy that permit to select backuped directories. The actual best solution is to use the root filesystem policy type to backup all directories or use the piped backup with a tar/squashfs command.

**Comment by GaetanF** [comment]
I will integrate this policy type in the next major release.

**Comment by GaetanF** [comment]
Hello,

This feature have been implemented on develop branch [#772dfa](https://github.com/cyborgbackup/cyborgbackup/commit/772dfa70e3c5a6b4db3d5014e73b8c35ac248a1b)

**Comment by GaetanF** [comment]
Hello,

This feature have been merged on the latest release v0.4.

Regards
