### ISSUE TITLE
error in prepare client

### ISSUE THREAD

**Issue by ltgentoo** [cyborgbackup/cyborgbackup#21]
the error is:
Enter passphrase for /tmp/cyborgbackup_72_3zjwwfat/credential_cyborgbackup_ssh_key

i install cyborgbackup use docker-compose
 it looks like to need input the ssh_key password,i read the doc,but could not find how to config this,help me ,thanks

**Comment by ltgentoo** [comment]
how to config the ssh key and ssh password?

**Comment by TrofimovVS** [comment]
You need generate rsa keys. 
`ssh-keygen` 
Next step: add to settings ui in field "Ssh Key" private key. In client add in ~/.ssh/authorized_keys public key.

**Comment by ltgentoo** [comment]
thans,although there are still other problems,at least prepare client works fine
