### ISSUE TITLE
Use https instead of git in requirements.txt

### ISSUE THREAD

**Issue by bolet** [cyborgbackup/cyborgbackup#24]
When building the docker image behind a relatively restrictive proxy, the command `git clone -q git://github.com/GaetanF/django-elasticsearch-dsl-drf` throws an error.

Simply using `https://github.com/GaetanF/django-elasticsearch-dsl-drf.git` instead fixes the issue.

**Comment by GaetanF** [comment]
Hello,

Elasticsearch will be removed in the next release. The stack is too difficult too maintain with Python development and Elasticsearch need more specific configurations for big catalog import (>5M items).
