### ISSUE TITLE
cyborgbackup/cyborgbackup:latest not on the Docker Hub?

### ISSUE THREAD

**Issue by jcrben** [cyborgbackup/cyborgbackup#27]
The instructions at https://cyborgbackup.readthedocs.io/en/latest/user/install.html#install refer to `wget https://raw.githubusercontent.com/cyborgbackup/cyborgbackup/master/docker-compose.yml` which has `cyborgbackup/cyborgbackup:latest`. As far as I can tell, this does not exist on the Docker Hub, and therefore I got this error message:

![image](https://user-images.githubusercontent.com/5614134/78508281-5e2c6e00-773a-11ea-8283-24d4f34064c6.png)

I switched it to milkywan/cyborgbackup:latest per https://hub.docker.com/r/milkywan/cyborgbackup and managed to get the app up and running, but I think it's an old version from 2018.

**Comment by Hjord** [comment]
Same problem here.

**Comment by GaetanF** [comment]
Hello,

I'm currently redevelop the UI interface using Angular 8. I will separate Frontend and Backend in two container and package.

The Docker container will be automatically build by GitHub on master push after this release.

Regards

**Comment by ThorpeJosh** [comment]
I am looking to try cyborgbackup out  and using the instructions in the docs I ran into the same problem.
Can I try an older version in the meantime?

**Comment by ikkemaniac** [comment]
> I am looking to try cyborgbackup out and using the instructions in the docs I ran into the same problem.
> 
> I tried the docker image from milkywan/cyborgbackup:latest but I can't login, the email and password doesn't match the docs

what happens when you start the docker and try to create a user/pwd using this:

```
$ docker-compose exec web /bin/bash
web$ python3 /cyborgbackup/manage.py loaddata settings
web$ echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin@cyborg.local', 'admin')" | python3 /cyborgbackup/manage.py shell
web$ exit
```
from here: https://cyborgbackup.readthedocs.io/en/latest/user/install.html#docker-compose-up

**Comment by ThorpeJosh** [comment]
Ah Thanks!
That is my bad. I didn't finish all the way through the instructions. I edited the docker compose file to point to the old docker-hub repo and presumed I was finished.

**Comment by henfri** [comment]
Hello,

the web container is currently not defined in the docker-compose.yml.

Regards,
Hendrik

**Comment by GaetanF** [comment]
Hello,

The Github Actions are currently running to build the latest image from the Master branch.

Regards

**Comment by henfri** [comment]
Works now. Thanks!

**Comment by GaetanF** [comment]
Hello,

Latest version are built on each push on Master branch now. Develop version are built on each push on Develop branch.

Gaëtan
