### ISSUE TITLE
Unable to connect to the interface

### ISSUE THREAD

**Issue by masterbalby2** [cyborgbackup/cyborgbackup#40]
Hello everyone and bravo for this project.
I'm trying to install cyborgbackup using the method from source code and docker.
I think the installation is going well but when I try to connect to the interface from http://localhost:8000, I get to the following page and not the authentication page
.
A little help would be welcome.
Cédric

![Capture d’écran 2020-10-22 à 14 28 23](https://user-images.githubusercontent.com/70953003/96871644-dc502800-1472-11eb-922b-6b266dfbdfbc.png)

**Comment by masterbalby2** [comment]
I finally manage to display the authentication page (by redirecting port 80 on the 8080 of the ui) but when I enter the login and password (admin@cyborg.local and admin) and click on "LOG IN" the box gets gray and nothing happens.

**Comment by GaetanF** [comment]
Hello,

I have updated the docker-compose file. The UI run under the 8088 port and the API on the 8000 port, you need to use "Specific CyBorg server" and set the URL to http://localhost:8000

Regards

**Comment by masterbalby2** [comment]
it works. Great. Now we just have to set it up.

thanks again
