### ISSUE TITLE
how to add an existing repository that does not have an repository key

### ISSUE THREAD

**Issue by masterbalby2** [cyborgbackup/cyborgbackup#41]
as the title of the topic indicates, can we add an existing repository that was created without a repository key.
Thank you

**Comment by GaetanF** [comment]
Hello,

I'm not sure that you can add an existing repository previously created without a passphrase. The BORG_PASSPHRASE are setted with the Repository Key value and I don't know how borg will work with an empty value.
If you have an existing repository with a passphrase, you can add them using the API and force the "ready" value with the API.

Regards

**Comment by masterbalby2** [comment]
And if the repository is on the same machine as cyborgbackup, what path should we enter in the "path" field of the "add repo" section

**Comment by GaetanF** [comment]
This field must be filled with a valid uri like SCP Uri even if it's hosted on the same machine as cyborgbackup.

This URI will be used on the clients to remotely access repository.
