### ISSUE TITLE
Docker behind reverse proxy

### ISSUE THREAD

**Issue by bambuleee** [cyborgbackup/cyborgbackup#52]
I'm running the containers behind traefik.
When opening the UI over the loadbalancer url (https://mydomain.local, CyBorg Server Address: http://host:8000), i can't login:

Http failure response for http://host:8000/api/login/: 0 Unknown Error

When changing https://mydomain.local to http://host:8088 it's working

Edit: http is working

**Comment by GaetanF** [comment]
Hello,

If an issue is related to the UI, could you open issue on the cyborgbackup-ui project. It will be better to follow them.

For this issue, zymbiosis have push a PR in develop branch so you can update your cyborgbackup-ui docker image to the latest develop tag.

Regards
