### ISSUE TITLE
prune job failed

### ISSUE THREAD

**Issue by pepz-de** [cyborgbackup/cyborgbackup#54]
Fresh installation (docker), back job and catalog job runs successfull, prune job fails with:

Identity added: /tmp/cyborgbackup_15_kar_w5ge/credential_cyborgbackup_ssh_key (cyborg@cyborg.loca
sh: 1: borg: not found

**Comment by hugalafutro** [comment]
Hi,
I have set up fresh docker install of cyborgbackup and still ran into this issue. I had to run `apt-get update && apt-get install -y borgbackup` inside the `cyborgbackup-celery` container to fix.
